# 配置地址
# https://everfind.github.io/tools/ls-lint.html#%E9%85%8D%E7%BD%AE
# 配置
# # 需要 npm add @ls-lint/ls-lint
# # 在 package.json 中， scripts 中，运行命令中
### 例： "dev": "ls-lint && vite",
ls:
    .js: camelCase | kebab-case
    .ts: kebab-case | point.case
    .json: kebab-case | point.case
    .vue: PascalCase
    .tsx: kebab-case | point.case | camelCase | PascalCase
    .d.ts: kebab-case | point.case
ignore:
    - node_modules
