/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    AWatermark: typeof import("ant-design-vue/es")["Watermark"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
